### ISSUE TITLE
text: type constraint checking

### ISSUE THREAD

**Issue by masebast** [ButterFaces/ButterFaces#217] opened 2018-12-17 17:20 UTC
I set the type of a text element to 'number' and min and max attributes to 1 and 4 respectively. Entering the value 5 followed by submit will briefly highlight the input box in red while still accepting the input value. Entering a value below the specified minimum will result in the same behaviour. 

I expected an invalid input value to be rejected as is the case with the check on string length when applying the ValidateLength attribute.

**Comment by masebast** [comment] 2018-12-18 15:59
I used Firefox version 60.3.0.esr. I just tried with Internet Explorer version 11.09600. Again the incorrect input is accepted but this time without the brief red frame that I see with Firefox.

By the way:  I'd consider the bevaviour you described in your comment, i.e. replacing the incorrect value by a valid one, as a serious bug, too. It is as if the application said: "I don't like the value you submitted, so I'll take one I like instead." An incorrect value should neither be accepted nor replaced by a valid one.

**Comment by larmic** [comment] 2018-12-22 16:03
@szerhusenBC what is your opinion?

**Comment by szerhusenBC** [comment] 2019-10-16 16:29
@larmic isn't this a duplicate of #193?

**Comment by larmic** [comment] 2020-12-22 09:34
Close because of inactivity. If this behavior is still incorrect or unwanted, please create a new issue.

**Closed by larmic** 2020-12-22 09:34 UTC
Labels: bug, showcase
