### ISSUE TITLE
Showcase - commandLink - ajaxHideGlyphicon does not work

### ISSUE THREAD

**Issue by masebast** [ButterFaces/ButterFaces#169] opened 2018-02-15 17:58 UTC
When checking the attribute ajaxHideGlyphicon the icon on the button remains. It was expected that the attribute toggles the display of the icon.

**Comment by larmic** [comment] 2018-02-20 18:49
The property means that no glyphicon is shown, when ajax request is running. To remove glyphicon you have to set glyphicon attribute. 

It works as intended.

I will close it for now.

**Closed by larmic** 2018-02-20 18:49 UTC
Labels: question
